name: Codeberg mirror

on:
  push:
    branches:
      - "**"

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts
          echo "${{ secrets.CODEBERG_SSH_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add ~/.ssh/github_actions

      - name: Push to Codeberg
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git remote add codeberg ssh://git@codeberg.org/OliMoli/codeberg-mirror-test
          git push codeberg --force
